### ISSUE TITLE
[PM] Discuss/confirm merging the SCI Data and Guidance projects

### ISSUE THREAD

**Issue by dohafernandez** [Green-Software-Foundation/software_carbon_intensity_data#28]
**What:** There are two projects that are closely related (Data & Guidance) being worked on separately. Asim decided that they should be merged to form one project.

@srini1978 @navveenb 

**How:**
- [ ] Discuss with SWG how the projects can be merged
- [ ] Agree on how it will be managed and by who
- [ ] Build governance around how the repo will be maintained
- [ ] Who will be the project leads
- [ ] Who will take care of the review process 

Related issue #27

**Comment by seanmcilroy29** [comment]
Done
