### ISSUE TITLE
Carbon calculator based on SCI Guidance for quick analysis of different architectural solutions

### ISSUE THREAD

**Issue by plnoel** [Green-Software-Foundation/software_carbon_intensity_data#41]
Hi there, we've been following the SCI guidance and we realize it takes time for an engineer to capture all that insight and quickly put it in practice to evaluate the impact of two potential architectural solutions. So we were wondering if there is (or if there is any plan of creating) a 'simple carbon calculator' that can help engineer quickly evaluate whether a solution A which would require x cpu, y memory, z storage, α network in cloud c in region r at time t, is better or worse than a solution B which would require x' cpu, y' memory, z' storage, α' network in cloud c' in region r' at time t' ? a bit like [this calculator](http://calculator.green-algorithms.org/), but more comprehensive and leveraging the recommendations from the sci guidance.
If not is this something we should consider starting as part of the open-source working group?

**Comment by srini1978** [comment]
We have started the project https://github.com/Green-Software-Foundation/carbon-ql  that is meant to solve the same problem. Please join in and provide your contributions. Tagging @Oleg-Zhymolokhov who is the project manager.

**Comment by plnoel** [comment]
@srini1978  sounds good, keep me in the loop, we'll try to help where we can. Do you plan a web app in that context as well or just an API?

**Comment by srini1978** [comment]
@plnoel  We can also plan a web app that can be leveraged as an easy way for consumers to call the API. Great idea  @navveenb @GadhuNTTDATA . Attached the label of  Enhancement to this issue

**Comment by srini1978** [comment]
Created the enhancement label for us to do it in carbonQL
