### ISSUE TITLE
[Bug]: https://sci-data.greensoftware.foundation/ can not be reached

### ISSUE THREAD

**Issue by pra** [Green-Software-Foundation/software_carbon_intensity_data#43]
### Contact Details

peter.antman@gmail.com

### What happened?

It's not possible to connect to https://sci-data.greensoftware.foundation/
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/197803/225301493-5d3cb2a3-87c5-4bce-a93f-f8459e425921.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srini1978** [comment]
@pra  Please use new URL - https://sci-guide.greensoftware.foundation/

**Comment by pra** [comment]
Thanks. Please update the link on https://learn.greensoftware.foundation/measurement to the new URL too.

**Comment by srini1978** [comment]
@pra  This is also done. Please check
