### ISSUE TITLE
Broken Links from SCI Quick Guide

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [Green-Software-Foundation/software_carbon_intensity_data#44]
**Describe the bug**
Links on the SCI Guide point to sci-data.greensoftware.foundation, which does not resolve.

**To Reproduce**
1. Go to ['...'](https://sci-guide.greensoftware.foundation/GettingStarted)
2. Click on any link e.g. 
Energy - For energy, we check the [list of options](https://sci-data.greensoftware.foundation/E) and select [API based techniques](https://sci-data.greensoftware.foundation/E/APIBased).
3. See error

**Expected behavior**
The linked page renders 😀  Appears that should instead be linking to sci-guide.greensoftware.foundation e.g. https://sci-guide.greensoftware.foundation/E

**Screenshots**
![image](https://user-images.githubusercontent.com/33758641/230653847-471e7877-e4d8-4110-91b0-d55a5cba1116.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Chrome

**Comment by srini1978** [comment]
Issue fixed @jonathan-m-hamilton
